### PR TITLE
DM-10410 Update starlink_ast

### PR DESCRIPTION
**Pull request by r-owen**
I'm trying to merge the latest AST in order to get a few fixes, including not stripping `TIMESYS` simplification of ChebyMap. I'm not entirely sure I merged from master correctly because the pull request includes things we've committed before.

### CODE REVIEW

**Comment by timj** [comment]
I think you need to change the base branch for this PR.

**Comment by timj** [comment]
In fact, I'll make lsst-dev the default branch on the repo.

**Comment by timj** [comment]
I've changed the base, I'll have a look at the commit history from my local checkout.

**Comment by timj** [comment]
I think this is happening because you merged master to your ticket branch and then are going to merge the ticket branch to lsst-dev. I think that's fine, it just makes the PR look a bit odd as upstream commits are involved.

**Comment by timj** [comment]
Now that I look in detail. I see. This PR is entirely for syncing up lsst-dev with master. I think this is how we have to do it since we don't want `lsst-dev` to be updated independently of `astshim`.

**Comment by r-owen** [comment]
Picking the wrong base certainly explains the confusing pull request. Thank you!

**Pull request merged**
